Governance:
  Q1: How does the company's board oversee climate-related risks and opportunities?
  Q2: What is the role of management in assessing and managing climate-related risks and opportunities?
Strategy:
  Q1: What are the most relevant climate-related risks and opportunities that the organisation has identified over the short, medium, and long term? Are risks clearly associated with a horizon?
  Q2: How do climate-related risks and opportunities impact the organisation's businesses strategy, economic and financial performance, and financial planning?
  Q3: How resilient is the organisation's strategy when considering different climate-related scenarios, including a 2°C target or lower scenario? How resilient is the organisation's strategy when considering climate physical risks?
Risk_Management:
  Q1: What processes does the organisation use to identify and assess climate-related risks?
  Q2: How does the organisation manage climate-related risks?
  Q3: How are the processes for identifying, assessing, and managing climate-related risks integrated into the organisation's overall risk management?
Metrics_and_Targets:
  Q1: What metrics does the organisation use to assess climate-related risks and opportunities? How do the metrics help ensure that the performance is in line with its strategy and risk management process?
  Q2: Does the organisation disclose its Scope 1, Scope 2, and, if appropriate, Scope 3 greenhouse gas (GHG) emissions? What are the related risks and do they differ depending on the scope?
  Q3: What targets does the organisation use to understand/quantify/benchmark climate-related risks and opportunities? How is the organization performing against these targets?
